
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://georgeburgess0827.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "George Burgess"
title: "{ George Burgess }"
description: "Blog and website of George Burgess, blogging mainly for tech, Music, Movies. Opinions expressed are mine."
keywords: "Burgess, George, Personal, jekyll, Blog, Website"
favicon: "/img/favicon.png"
404-img: ""
# new 404 #
505-img: "/img/404.jpg"
################
# Header layout #
################

black-favicon: "/img/alien.png"

background-img: "../img/skyline.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Failure is the condiment that gives success its flavor. -Truman Capote"
  - text: "If you fall, I’ll always be there. - The Floor"
  - text: "Even if you are on the right track, you’ll get run over if you just sit there. -Will Rogers"


me-img: "/img/profile.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: True
google-plus-share: False
tumblr-share: True
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: ""

syntax-highlight: True

############
# skills#
############
# skills:
#   - name: "Communication"
#     value: '9'
#   - name: "Organization"
#     value: '7'
#   - name: "Learning"
#     value: '10'
#   - name: "Teaching"
#     value: '6'
#   - name: "Planning"
#     value: '7'
#   - name: "Visual Design"
#     value: '5'
#   - name: "UXD Design"
#     value: '8'
#   - name: "Programming"
#     value: '6'

############
# Timeline #
############

events:
  - image: "/img/timeline/Timeline4.jpg"
    date: "August 2015 - Today"
    description: "Started the UXD M.S Program @ Kent State"
  - image: "/img/timeline/Timeline3.jpg"
    date: "Feburary 2015 - Today"
    description: "Landed My First Job As an Associate Software Engineer"
  - image: "/img/timeline/960.jpg"
    date: "August 2010 - December 2014"
    description: "Earned my B.S in Computer Science @ Tennessee State"

# First image of the Timeline

timeline-img: "/img/timeline/Timeline1.jpg"

###########
# Contact #
###########

email: "contact@georgeburgessjr.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/georgeburgessjr"
  - title: "twitter"
    url: "https://twitter.com/GeorgeBurgesJr"
  - title: "instagram"
    url: "https://instagram.com/georgeburgessjr"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/georgeburgessjr"
  - title: "github"
    url: "https://github.com/GeorgeBurgess0827"
  - title: "tumblr"
    url: "http://georgeburgess.tumblr.com"
  - title: "rss"
    url: "/feed.xml"

##################
# 505 (404) page #
##################

505-img: "/img/404.jpg"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
